### PR TITLE
Skip network idle event

### PR DESCRIPTION
**Pull request by rreynier**
Supports changes found: https://github.com/gotenberg/gotenberg/pull/749/files

### CODE REVIEW

**Comment by gulien** [comment]
Thanks @rreynier! I'll wait the release of Gotenberg v8 (~ end of the year) before merging this. In the meantime, you may directly use `formValue('skipNetworkIdleEvent', true);` 😄

**Comment by rreynier** [comment]
Oh right, didn't realize I could call options like that without the code. That works.

**Comment by rreynier** [comment]
Actually, the `formValue()` method is protected... so that may not work. Maybe I am missing something?

**Comment by rreynier** [comment]
Making it public is probably the most flexible approach IMO.

**Comment by gulien** [comment]
Feel free to open a PR 👍

**Comment by gulien** [comment]
Closing this in favor of #32.

**Pull request closed without merging**
